---
- name: Create project for ACME Controller
  openshift_project:
    name: "{{ appuio_openshift_acme_namespace }}"

- name: Instantiate ACME Controller template
  vars:
    acmeurl: "{{ appuio_openshift_acme_endpoint_alias[appuio_openshift_acme_endpoint] | default(appuio_openshift_acme_endpoint) }}"
  openshift_resource:
    namespace: "{{ appuio_openshift_acme_namespace }}"
    template: "{{ role_path }}/files/acme-controller-template.yml"
    arguments:
      OPENSHIFT_ACME_ACMEURL: "{{ acmeurl | mandatory }}"
      OPENSHIFT_ACME_LOGLEVEL: "{{ appuio_openshift_acme_loglevel | mandatory }}"
      DOCKER_IMAGE: "{{ appuio_openshift_acme_docker_image | mandatory }}"
      DOCKER_IMAGE_TAG: "{{ appuio_openshift_acme_docker_image_tag | mandatory }}"

- name: Cluster role assignement
  openshift_policy:
    cluster_roles:
    - acme-controller
    users: "system:serviceaccount:{{ appuio_openshift_acme_namespace }}:acme-controller"
