---
- name: Create project for ACME Controller
  openshift_project:
    name: "{{ namespace }}"

- name: Instantiate ACME Controller template
  openshift_resource:
    namespace: "{{ namespace }}"
    template: "{{ role_path }}/files/acme-controller-template.yml"
    arguments:
      OPENSHIFT_ACME_ACMEURL: "{{ acme_url | mandatory }}"
      OPENSHIFT_ACME_LOGLEVEL: "{{ acme_loglevel | default('8') }}"
      DOCKER_IMAGE: "{{ docker_image | default('docker.io/appuio/openshift-acme') }}"
      DOCKER_IMAGE_TAG: "{{ docker_image_tag | default('latest') }}"

- name: Cluster role assignement
  openshift_policy:
    cluster_roles:
    - acme-controller
    users: "system:serviceaccount:{{ namespace }}:acme-controller"
