apiVersion: v1
kind: Template
metadata:
  name: acme-controller
parameters:
- description: ACME Endpoint URL
  name: OPENSHIFT_ACME_ACMEURL
  value: https://acme-staging.api.letsencrypt.org/directory
- description: Controller loglevel
  name: OPENSHIFT_ACME_LOGLEVEL
  value: "8"
- description: Docker Image of ACME controller
  name: DOCKER_IMAGE
  value: docker.io/tnozicka/openshift-acme
- description: Docker Image Tag of ACME controller
  name: DOCKER_IMAGE_TAG
  value: latest
objects:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: acme-controller
    labels:
      app: acme-controller
  rules:
  - apiGroups:
    - "route.openshift.io"
    resources:
    - routes
    - routes/finalizers
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
  - apiGroups:
    - "route.openshift.io"
    resources:
    - routes/custom-host
    verbs:
    - create
    - update
    - delete
    - patch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - endpoints
    - endpoints/restricted
    - services
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - secrets
    - secrets/finalizers
    verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: acme-controller
    labels:
      app: acme-controller
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: acme-controller
    labels:
      app: acme-controller
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
      from:
        kind: DockerImage
        name: ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: acme-controller
    name: acme-controller
  spec:
    replicas: 1
    selector:
      app: acme-controller
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: acme-controller
      spec:
        containers:
        - env:
          - name: OPENSHIFT_ACME_EXPOSER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: OPENSHIFT_ACME_ACMEURL
            value: ${OPENSHIFT_ACME_ACMEURL}
          - name: OPENSHIFT_ACME_LOGLEVEL
            value: ${OPENSHIFT_ACME_LOGLEVEL}
          image: acme-controller:latest
          imagePullPolicy: Always
          name: acme-controller
          ports:
          - containerPort: 5000
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '500m'
              memory: '512Mi'
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: acme-controller
    test: false
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - acme-controller
        from:
          kind: ImageStreamTag
          name: acme-controller:latest
    - type: ConfigChange
